---
title: "BPDA_Time series"
author: "Weixiao Li"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(forecast)
library(tseries)
library(ggplot2)
library(ggfortify)
library(fpp)
library(vars)
library(readxl)
BPDA_Q1_1_ <- read_excel("C:/Users/16932/Desktop/BPDA Q1(1).xlsx")
BPDA <-BPDA_Q1_1_ 
BPDA <- ts(BPDA,start=2005,end=2019,frequency=1)

```

```{r}
#1
Income <- BPDA[, "Income"]
Income
ggtsdisplay(Income, main="Income series")
```

```{r}
# log transformation
log_Income <- log(Income)
ggtsdisplay(log_Income, main="log Income series")
log_Income <- log(Income)
```

```{r}
#Lag
Income <- as.integer(Income)
lag(Income, k=-1)
Income <- lag(Income, k=-1)
diff(Income, lag=1)
log_diff <- diff(log_Income)
ggtsdisplay(log_diff, xlab="x",ylab="y",main="log difference")

```

```{r}
#Frequency
frequency(Income)
diff(Income, lag=frequency(Income))
seas_log_diff <- diff(log_diff, lag=frequency(log_diff))
ggtsdisplay(seas_log_diff, main="Yearly differenced income")

```

```{r}
# Auto correlation function and partial auto correlation function
acf(seas_log_diff, plot=F, lag.max=12)
pacf(seas_log_diff, plot=F, lag.max=12)
autoplot(
  acf(seas_log_diff, plot=F), 
  main="Corellogram of log differenced series"
)
```

```{r}
## ARIMA 
BPDA_FLO <- BPDA[,c("Income", "Citizen", "Not a Citizen")]
train <- window(BPDA, end=c(2013))
test <- window(BPDA, start=c(2014))
Citizen_Not<- train[, c("Citizen", "Not a Citizen")]
model_arima <- Arima(
  y = train[, "Income"], 
  order = c(1, 1, 1),
  seasonal = list(order = c(0, 1, 0))
)

model_arima
checkresiduals(model_arima)
```

```{r}
#Auto ARIMA
I_C_N <- auto.arima(
  y = train[, "Income"], 
  xreg = Citizen_Not,
  ic = "aic",
  max.order = 7,
  stepwise = F,
  approximation = F,
  parallel = T,
  num.cores = 1
)
I_C_N
```
